# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: gobgp.proto for package 'gobgpapi'

require 'grpc'
require 'gobgp'

module Gobgpapi
  module GobgpApi

    # TODO: add proto service documentation here
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'gobgpapi.GobgpApi'

      rpc :GetGlobalConfig, Arguments, Global
      rpc :ModGlobalConfig, ModGlobalConfigArguments, Error
      rpc :GetNeighbors, Arguments, stream(Peer)
      rpc :GetNeighbor, Arguments, Peer
      rpc :ModNeighbor, ModNeighborArguments, Error
      rpc :GetRib, Table, Table
      rpc :Reset, Arguments, Error
      rpc :SoftReset, Arguments, Error
      rpc :SoftResetIn, Arguments, Error
      rpc :SoftResetOut, Arguments, Error
      rpc :Shutdown, Arguments, Error
      rpc :Enable, Arguments, Error
      rpc :Disable, Arguments, Error
      rpc :ModPath, ModPathArguments, ModPathResponse
      rpc :ModPaths, stream(ModPathsArguments), Error
      rpc :MonitorBestChanged, Arguments, stream(Destination)
      rpc :MonitorPeerState, Arguments, stream(Peer)
      rpc :GetMrt, MrtArguments, stream(MrtMessage)
      rpc :ModMrt, ModMrtArguments, Error
      rpc :GetRPKI, Arguments, stream(RPKI)
      rpc :ModRPKI, ModRpkiArguments, Error
      rpc :GetROA, Arguments, stream(ROA)
      rpc :GetVrfs, Arguments, stream(Vrf)
      rpc :ModVrf, ModVrfArguments, Error
      rpc :GetDefinedSet, DefinedSet, DefinedSet
      rpc :GetDefinedSets, DefinedSet, stream(DefinedSet)
      rpc :ModDefinedSet, ModDefinedSetArguments, Error
      rpc :GetStatement, Statement, Statement
      rpc :GetStatements, Statement, stream(Statement)
      rpc :ModStatement, ModStatementArguments, Error
      rpc :GetPolicy, Policy, Policy
      rpc :GetPolicies, Policy, stream(Policy)
      rpc :ModPolicy, ModPolicyArguments, Error
      rpc :GetPolicyAssignment, PolicyAssignment, PolicyAssignment
      rpc :ModPolicyAssignment, ModPolicyAssignmentArguments, Error
    end

    Stub = Service.rpc_stub_class
  end
end
